import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/adoption_report.dart';

Future<void> generateAdoptionReportPdf(
  AdoptionReport report,
  String generatedBy,
) async {
  final regularFont = pw.Font.ttf(
    await rootBundle.load(
      "assets/fonts/Roboto-Regular.ttf",
    ),
  );

  final boldFont = pw.Font.ttf(
    await rootBundle.load(
      "assets/fonts/Roboto-Bold.ttf",
    ),
  );

  final pdf = pw.Document(
    theme: pw.ThemeData.withFont(
      base: regularFont,
      bold: boldFont,
    ),
  );

  final double approvalRate =
      report.totalRequests == 0
          ? 0
          : (report.approvedRequests * 100) /
              report.totalRequests;

  final requestsByStatus = {
    "Pending": report.pendingRequests,
    "Approved": report.approvedRequests,
    "Rejected": report.rejectedRequests,
    "Cancelled": report.cancelledRequests,
  };

  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      build: (context) => [

        pw.Center(
          child: pw.Text(
            "eAnimalShelter",
            style: pw.TextStyle(
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),

        pw.Center(
          child: pw.Text(
            "ADOPTION REPORT",
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),

        pw.SizedBox(height: 15),

        pw.Text(
          "Generated: ${DateFormat("dd.MM.yyyy HH:mm").format(DateTime.now())}",
        ),

        pw.Text(
          "Generated by: $generatedBy",
        ),

        pw.Divider(),

        pw.SizedBox(height: 10),

        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(),
          ),
          child: pw.Column(
            crossAxisAlignment:
                pw.CrossAxisAlignment.start,
            children: [

              pw.Text(
                "SUMMARY",
                style: pw.TextStyle(
                  fontWeight:
                      pw.FontWeight.bold,
                ),
              ),

              pw.SizedBox(height: 10),

              pw.Text(
                "Total Requests: ${report.totalRequests}",
              ),

              pw.Text(
                "Pending Requests: ${report.pendingRequests}",
              ),

              pw.Text(
                "Approved Requests: ${report.approvedRequests}",
              ),

              pw.Text(
                "Rejected Requests: ${report.rejectedRequests}",
              ),

              pw.Text(
                "Cancelled Requests: ${report.cancelledRequests}",
              ),

              pw.SizedBox(height: 5),

              pw.Text(
                "Approval Rate: ${approvalRate.toStringAsFixed(1)} %",
              ),
            ],
          ),
        ),

        pw.SizedBox(height: 25),

        pw.Text(
          "Requests By Status",
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight:
                pw.FontWeight.bold,
          ),
        ),

        pw.SizedBox(height: 10),

        pw.Table(
          border:
              pw.TableBorder.all(),
          children: [

            pw.TableRow(
              decoration:
                  const pw.BoxDecoration(
                color:
                    PdfColors.grey300,
              ),
              children: [

                pw.Padding(
                  padding:
                      const pw.EdgeInsets.all(
                          8),
                  child: pw.Text(
                    "Status",
                    style: pw.TextStyle(
                      fontWeight:
                          pw.FontWeight
                              .bold,
                    ),
                  ),
                ),

                pw.Padding(
                  padding:
                      const pw.EdgeInsets.all(
                          8),
                  child: pw.Text(
                    "Requests",
                    style: pw.TextStyle(
                      fontWeight:
                          pw.FontWeight
                              .bold,
                    ),
                  ),
                ),
              ],
            ),

            ...requestsByStatus.entries.map(
              (entry) => pw.TableRow(
                children: [

                  pw.Padding(
                    padding:
                        const pw.EdgeInsets.all(
                            8),
                    child: pw.Text(
                      entry.key,
                    ),
                  ),

                  pw.Padding(
                    padding:
                        const pw.EdgeInsets.all(
                            8),
                    child: pw.Text(
                      entry.value
                          .toString(),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),

        pw.SizedBox(height: 30),

        pw.Divider(),

        pw.Align(
          alignment:
              pw.Alignment.centerRight,
          child: pw.Column(
            crossAxisAlignment:
                pw.CrossAxisAlignment
                    .end,
            children: [

              pw.Text(
                "Generated by:",
                style:
                    const pw.TextStyle(
                  fontSize: 10,
                ),
              ),

              pw.Text(
                generatedBy,
                style: pw.TextStyle(
                  fontSize: 12,
                  fontWeight:
                      pw.FontWeight.bold,
                ),
              ),
            ],
          ),
        ),
      ],
    ),
  );

  await Printing.layoutPdf(
    onLayout: (_) async => pdf.save(),
  );
}