import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:flutter/services.dart';

import '../models/donation_report.dart';

Future<void> generateDonationReportPdf(
  DonationReport report,
  String generatedBy,
) async {
  final regularFont = pw.Font.ttf(
    await rootBundle.load(
      "assets/fonts/Roboto-Regular.ttf",
    ),
  );

  final boldFont = pw.Font.ttf(
    await rootBundle.load(
      "assets/fonts/Roboto-Bold.ttf",
    ),
  );
  final pdf = pw.Document(
    theme: pw.ThemeData.withFont(
      base: regularFont,
      bold: boldFont,
    ),
  );

  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      build: (context) => [

        pw.Center(
          child: pw.Text(
            "eAnimalShelter",
            style: pw.TextStyle(
              fontSize: 24,
              fontWeight:
                  pw.FontWeight.bold,
            ),
          ),
        ),

        pw.Center(
          child: pw.Text(
            "DONATION REPORT",
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight:
                  pw.FontWeight.bold,
            ),
          ),
        ),

        pw.SizedBox(height: 15),

       pw.Text(
          "Generated: ${DateFormat("dd.MM.yyyy HH:mm").format(DateTime.now())}",
        ),

        pw.Text(
          "Generated by: $generatedBy",
        ),

        pw.Divider(),

        pw.SizedBox(height: 10),

        pw.Container(
          padding:
              const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border:
                pw.Border.all(),
          ),
          child: pw.Column(
            crossAxisAlignment:
                pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                "SUMMARY",
                style: pw.TextStyle(
                  fontWeight:
                      pw.FontWeight.bold,
                ),
              ),

              pw.SizedBox(height: 10),

              pw.Text(
                "Total Donations: ${report.totalDonations.toStringAsFixed(2)} KM",
              ),

              pw.Text(
                "Average Donation: ${report.averageDonation.toStringAsFixed(2)} KM",
              ),

              pw.Text(
                "Top Donor: ${report.topDonor}",
              ),
            ],
          ),
        ),

        pw.SizedBox(height: 25),

        pw.Text(
          "Donations By Month",
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight:
                pw.FontWeight.bold,
          ),
        ),

        pw.SizedBox(height: 10),

        pw.Table(
          border:
              pw.TableBorder.all(),
          children: [

            pw.TableRow(
              decoration:
                  const pw.BoxDecoration(
                color: PdfColors.grey300,
              ),
              children: [
                pw.Padding(
                  padding:
                      const pw.EdgeInsets.all(
                          8),
                  child: pw.Text(
                    "Month",
                    style: pw.TextStyle(
                      fontWeight:
                          pw.FontWeight.bold,
                    ),
                  ),
                ),
                pw.Padding(
                  padding:
                      const pw.EdgeInsets.all(
                          8),
                  child: pw.Text(
                    "Amount",
                    style: pw.TextStyle(
                      fontWeight:
                          pw.FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),

            ...report.donationsByMonth.entries
                .map(
                  (e) => pw.TableRow(
                    children: [
                      pw.Padding(
                        padding:
                            const pw.EdgeInsets.all(
                                8),
                        child: pw.Text(
                          e.key,
                        ),
                      ),
                      pw.Padding(
                        padding:
                            const pw.EdgeInsets.all(
                                8),
                        child: pw.Text(
                          "${e.value.toStringAsFixed(2)} KM",
                        ),
                      ),
                    ],
                  ),
                ),
          ],
        ),

        pw.SizedBox(height: 30),

        pw.Divider(),

        pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Column(
            crossAxisAlignment:
                pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                "Generated by:",
                style: const pw.TextStyle(
                  fontSize: 10,
                ),
              ),
              pw.Text(
                generatedBy,
                style: pw.TextStyle(
                  fontSize: 12,
                  fontWeight:
                      pw.FontWeight.bold,
                ),
              ),
            ],
          ),
        ),
      ],
    ),
  );

  await Printing.layoutPdf(
    onLayout: (_) async =>
        pdf.save(),
  );
}